//==============================================================================
// Darkest Hour: Europe '44-'45
// Darklight Games (c) 2008-2015
//==============================================================================

class DH_HellcatCannon extends DHVehicleCannon;

defaultproperties
{
    InitialTertiaryAmmo=10
    TertiaryProjectileClass=class'DH_Vehicles.DH_HellcatCannonShellHE'
    SecondarySpread=0.001
    TertiarySpread=0.00135
    ManualRotationsPerSecond=0.033
    PoweredRotationsPerSecond=0.067
    FrontArmorFactor=1.9
    RightArmorFactor=1.3
    LeftArmorFactor=1.3
    RearArmorFactor=1.3
    RightArmorSlope=20.0
    LeftArmorSlope=20.0
    RearArmorSlope=13.0
    FrontLeftAngle=324.0
    FrontRightAngle=36.0
    RearRightAngle=144.0
    RearLeftAngle=216.0
    ReloadSoundOne=sound'DH_Vehicle_Reloads.Reloads.reload_01s_01'
    ReloadSoundTwo=sound'DH_Vehicle_Reloads.Reloads.reload_01s_02'
    ReloadSoundThree=sound'DH_Vehicle_Reloads.Reloads.reload_02s_03'
    ReloadSoundFour=sound'DH_Vehicle_Reloads.Reloads.reload_01s_04'
    CannonFireSound(0)=SoundGroup'Vehicle_Weapons.T34_85.85mm_fire01'
    CannonFireSound(1)=SoundGroup'Vehicle_Weapons.T34_85.85mm_fire02'
    CannonFireSound(2)=SoundGroup'Vehicle_Weapons.T34_85.85mm_fire03'
    ProjectileDescriptions(0)="APCBC"
    ProjectileDescriptions(1)="HVAP"
    ProjectileDescriptions(2)="HE"
    AddedPitch=52
    YawBone="Turret"
    PitchBone="Gun"
    PitchUpLimit=15000
    PitchDownLimit=45000
    WeaponFireAttachmentBone="Barrel"
    GunnerAttachmentBone="com_attachment"
    WeaponFireOffset=-4.0
    FireInterval=5.0
    FireSoundVolume=512.0
    FireForce="Explosion05"
    ProjectileClass=class'DH_Vehicles.DH_HellcatCannonShell'
    ShakeRotMag=(Z=50.0)
    ShakeRotRate=(Z=1000.0)
    ShakeRotTime=4.0
    ShakeOffsetMag=(Z=1.0)
    ShakeOffsetRate=(Z=100.0)
    ShakeOffsetTime=10.0
    AIInfo(0)=(bLeadTarget=true,WarnTargetPct=0.75,RefireRate=0.5)
    AIInfo(1)=(bLeadTarget=true,WarnTargetPct=0.75,RefireRate=0.015)
    CustomPitchUpLimit=3641
    CustomPitchDownLimit=63715
    BeginningIdleAnim="com_idle_close"
    InitialPrimaryAmmo=30
    InitialSecondaryAmmo=5
    PrimaryProjectileClass=class'DH_Vehicles.DH_HellcatCannonShell'
    SecondaryProjectileClass=class'DH_Vehicles.DH_HellcatCannonShellHVAP'
    FireEffectScale=1.5 // turret fire is larger & positioned in centre of open turret
    FireEffectOffset=(X=15.0,Y=30.0,Z=0.0)
    Mesh=SkeletalMesh'DH_Hellcat_anm.hellcat_turret_ext'
    Skins(0)=texture'DH_VehiclesUS_tex5.ext_vehicles.hellcat_turret_ext'
    Skins(1)=texture'DH_VehiclesUS_tex5.int_vehicles.hellcat_turret_int'
    SoundVolume=130
    SoundRadius=300.0
}
