//==============================================================================
// Darkest Hour: Europe '44-'45
// Darklight Games (c) 2008-2015
//==============================================================================

class DH_HetzerCannon extends DH_ROTankCannon;

defaultproperties
{
    InitialTertiaryAmmo=5
    TertiaryProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL48CannonShellSmoke'
    SecondarySpread=0.00127
    ManualRotationsPerSecond=0.025
    bIsAssaultGun=true
    GunMantletArmorFactor=6.0
    GunMantletSlope=40.0
    ReloadSoundOne=sound'DH_Vehicle_Reloads.Reloads.reload_02s_01'
    ReloadSoundTwo=sound'DH_Vehicle_Reloads.Reloads.reload_02s_02'
    ReloadSoundThree=sound'DH_Vehicle_Reloads.Reloads.reload_02s_03'
    ReloadSoundFour=sound'DH_Vehicle_Reloads.Reloads.reload_02s_04'
    CannonFireSound(0)=SoundGroup'Vehicle_Weapons.PanzerIV_F2.75mm_L_fire01'
    CannonFireSound(1)=SoundGroup'Vehicle_Weapons.PanzerIV_F2.75mm_L_fire02'
    CannonFireSound(2)=SoundGroup'Vehicle_Weapons.PanzerIV_F2.75mm_L_fire03'
    ProjectileDescriptions(0)="APCBC"
    ProjectileDescriptions(2)="Smoke"
    RangeSettings(1)=100
    RangeSettings(2)=200
    RangeSettings(3)=300
    RangeSettings(4)=400
    RangeSettings(5)=500
    RangeSettings(6)=600
    RangeSettings(7)=700
    RangeSettings(8)=800
    RangeSettings(9)=900
    RangeSettings(10)=1000
    RangeSettings(11)=1100
    RangeSettings(12)=1200
    RangeSettings(13)=1300
    RangeSettings(14)=1400
    RangeSettings(15)=1500
    RangeSettings(16)=1600
    RangeSettings(17)=1700
    RangeSettings(18)=1800
    RangeSettings(19)=1900
    RangeSettings(20)=2000
    RangeSettings(21)=2200
    RangeSettings(22)=2400
    RangeSettings(23)=2600
    RangeSettings(24)=2800
    RangeSettings(25)=3000
    MinCommanderHitHeight=15.0;
    VehHitpoints(0)=(PointRadius=8.0,PointScale=1.0,PointBone="com_attachment",PointOffset=(Z=24.799999))
    VehHitpoints(1)=(PointRadius=16.0,PointScale=1.0,PointBone="com_attachment",PointOffset=(X=-8.0,Z=2.4))
    hudAltAmmoIcon=texture'InterfaceArt_tex.HUD.mg42_ammo'
    YawBone="Turret"
    YawStartConstraint=-2000.0
    YawEndConstraint=3000.0
    PitchBone="gun_pitch"
    WeaponFireAttachmentBone="Gun"
    GunnerAttachmentBone="com_attachment"
    WeaponFireOffset=160.0
    EffectEmitterClass=class'ROEffects.TankCannonFireEffect'
    FireSoundVolume=512.0
    FireForce="Explosion05"
    ProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL48CannonShell'
    ShakeRotMag=(Z=50.0)
    ShakeRotRate=(Z=1000.0)
    ShakeRotTime=4.0
    ShakeOffsetMag=(Z=1.0)
    ShakeOffsetRate=(Z=100.0)
    ShakeOffsetTime=10.0
    AIInfo(0)=(bLeadTarget=true,WarnTargetPct=0.75,RefireRate=0.5)
    AIInfo(1)=(bLeadTarget=true,WarnTargetPct=0.75,RefireRate=0.015)
    CustomPitchUpLimit=1820
    CustomPitchDownLimit=64444
    MaxPositiveYaw=2000
    MaxNegativeYaw=-910
    bLimitYaw=true
    BeginningIdleAnim="com_idle_close"
    InitialPrimaryAmmo=30
    InitialSecondaryAmmo=10
    PrimaryProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL48CannonShell'
    SecondaryProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL48CannonShellHE'
    Mesh=SkeletalMesh'DH_Hetzer_anm_V1.hetzer_turret'
    Skins(0)=texture'DH_Hetzer_tex_V1.hetzer_body'
    SoundVolume=130
    SoundRadius=200.0
}
