//==============================================================================
// Darkest Hour: Europe '44-'45
// Darklight Games (c) 2008-2015
//==============================================================================

class DH_JagdpanzerIVL70Cannon extends DHVehicleCannon;

defaultproperties
{
    InitialTertiaryAmmo=15
    TertiaryProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL70CannonShellHE'
    SecondarySpread=0.00165
    TertiarySpread=0.0012
    ManualRotationsPerSecond=0.025
    bHasTurret=false
    GunMantletArmorFactor=8.0
    GunMantletSlope=40.0
    ReloadSoundOne=sound'Vehicle_reloads.Reloads.STUG_III_reload_01'
    ReloadSoundTwo=sound'Vehicle_reloads.Reloads.STUG_III_reload_02'
    ReloadSoundThree=sound'Vehicle_reloads.Reloads.STUG_III_reload_03'
    ReloadSoundFour=sound'Vehicle_reloads.Reloads.STUG_III_reload_04'
    CannonFireSound(0)=SoundGroup'Vehicle_Weapons.Panther.75mm_VL_fire01'
    CannonFireSound(1)=SoundGroup'Vehicle_Weapons.Panther.75mm_VL_fire02'
    CannonFireSound(2)=SoundGroup'Vehicle_Weapons.Panther.75mm_VL_fire03'
    ProjectileDescriptions(1)="APCR"
    ProjectileDescriptions(2)="HE"
    RangeSettings(1)=100
    RangeSettings(2)=200
    RangeSettings(3)=300
    RangeSettings(4)=400
    RangeSettings(5)=500
    RangeSettings(6)=600
    RangeSettings(7)=700
    RangeSettings(8)=800
    RangeSettings(9)=900
    RangeSettings(10)=1000
    RangeSettings(11)=1100
    RangeSettings(12)=1200
    RangeSettings(13)=1300
    RangeSettings(14)=1400
    RangeSettings(15)=1500
    RangeSettings(16)=1600
    RangeSettings(17)=1700
    RangeSettings(18)=1800
    RangeSettings(19)=1900
    RangeSettings(20)=2000
    RangeSettings(21)=2200
    RangeSettings(22)=2400
    RangeSettings(23)=2600
    RangeSettings(24)=2800
    RangeSettings(25)=3000
    YawStartConstraint=-3000.0
    YawEndConstraint=3000.0
    PitchBone="Turret"
    GunnerAttachmentBone="Commander_attachment"
    WeaponFireOffset=6.0
    ProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL70CannonShell'
    CustomPitchUpLimit=2731
    CustomPitchDownLimit=64653
    MaxPositiveYaw=1820
    MaxNegativeYaw=-1820
    bLimitYaw=true
    InitialPrimaryAmmo=35
    InitialSecondaryAmmo=5
    PrimaryProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL70CannonShell'
    SecondaryProjectileClass=class'DH_Vehicles.DH_JagdpanzerIVL70CannonShellAPCR'
    FireEffectOffset=(X=10.0,Y=0.0,Z=0.0)
    Mesh=SkeletalMesh'DH_Jagdpanzer4_anm.jagdpanzer4L70_turret_ext'
    Skins(0)=texture'DH_VehiclesGE_tex4.ext_vehicles.jagdpanzeriv_body_camo1'
    Skins(1)=texture'DH_VehiclesGE_tex4.int_vehicles.jagdpanzeriv_body_int'
    Skins(2)=texture'DH_VehiclesGE_tex4.int_vehicles.jagdpanzeriv_body_int'
//  SoundRadius=300.0 // TODO: maybe change to 300 as this uses default 200, but is a powerful gun & this does not match panther's 300
}
