//==============================================================================
// Darkest Hour: Europe '44-'45
// Darklight Games (c) 2008-2015
//==============================================================================

class DH_StuH42Cannon extends DHVehicleCannon;

defaultproperties
{
    InitialTertiaryAmmo=10
    TertiaryProjectileClass=class'DH_Vehicles.DH_StuH42CannonShellHEAT'
    SecondarySpread=0.00357
    TertiarySpread=0.00275
    ManualRotationsPerSecond=0.025
    bHasTurret=false
    GunMantletArmorFactor=5.0
    GunMantletSlope=0.0
    ReloadSoundOne=sound'DH_Vehicle_Reloads.Reloads.reload_01s_01'
    ReloadSoundTwo=sound'DH_Vehicle_Reloads.Reloads.reload_01s_02'
    ReloadSoundThree=sound'DH_Vehicle_Reloads.Reloads.reload_01s_03'
    ReloadSoundFour=sound'DH_Vehicle_Reloads.Reloads.reload_01s_04'
    CannonFireSound(0)=SoundGroup'Vehicle_Weapons.Tiger.88mm_fire01'
    CannonFireSound(1)=SoundGroup'Vehicle_Weapons.Tiger.88mm_fire02'
    CannonFireSound(2)=SoundGroup'Vehicle_Weapons.Tiger.88mm_fire03'
    ProjectileDescriptions(0)="HE"
    ProjectileDescriptions(1)="Smoke"
    ProjectileDescriptions(2)="HEAT"
    RangeSettings(1)=100
    RangeSettings(2)=200
    RangeSettings(3)=300
    RangeSettings(4)=400
    RangeSettings(5)=500
    RangeSettings(6)=600
    RangeSettings(7)=700
    RangeSettings(8)=800
    RangeSettings(9)=900
    RangeSettings(10)=1000
    RangeSettings(11)=1100
    RangeSettings(12)=1200
    RangeSettings(13)=1300
    RangeSettings(14)=1400
    RangeSettings(15)=1500
    RangeSettings(16)=1600
    RangeSettings(17)=1700
    RangeSettings(18)=1800
    RangeSettings(19)=1900
    RangeSettings(20)=2000
    RangeSettings(21)=2200
    RangeSettings(22)=2400
    RangeSettings(23)=2600
    RangeSettings(24)=2800
    RangeSettings(25)=3000
    NumAltMags=4
    AltTracerProjectileClass=class'DH_Weapons.DH_MG34TracerBullet'
    AltFireTracerFrequency=7
    YawStartConstraint=-3000.0
    YawEndConstraint=3000.0
    PitchBone="Turret"
    WeaponFireOffset=-53.5
    AltFireOffset=(X=-167.0,Y=-10.0,Z=14.5)
    Spread=0.0015
    AltFireInterval=0.07
    AltFireSoundClass=SoundGroup'DH_WeaponSounds.mg34.mg34_fire_loop'
    AltFireEndSound=SoundGroup'DH_WeaponSounds.mg34.mg34_fire_end'
    ProjectileClass=class'DH_Vehicles.DH_StuH42CannonShellHE'
    AltFireProjectileClass=class'DH_Weapons.DH_MG34Bullet'
    CustomPitchUpLimit=3641
    CustomPitchDownLimit=64444
    MaxPositiveYaw=1820
    MaxNegativeYaw=-1820
    bLimitYaw=true
    InitialPrimaryAmmo=20
    InitialSecondaryAmmo=6
    InitialAltAmmo=150
    PrimaryProjectileClass=class'DH_Vehicles.DH_StuH42CannonShellHE'
    SecondaryProjectileClass=class'DH_Vehicles.DH_StuH42CannonShellSmoke'
    Mesh=SkeletalMesh'DH_Stug3G_anm.StuH_turret_ext'
    Skins(0)=texture'DH_VehiclesGE_tex2.ext_vehicles.Stug3g_body_ext'
    Skins(1)=texture'DH_VehiclesGE_tex2.int_vehicles.Stug3g_turret_int'
//  SoundVolume=200 // TODO: maybe change to 200 to match Sherman 105?
}
