name: 🐛 Bug Report
description: Create a report to help us improve the game 
labels: [bug]
body:
- type: textarea
  id: desc
  attributes:
    label: Describe the bug
    description: Provide a clear and concise description of what the bug is. Also tell us, what did you expect to happen?
  validations:
    required: true
- type: textarea
  id: repro
  attributes:
    label: Steps to reproduce
    description: What are the exact steps to reproduce this bug?.
    placeholder: |
      1. Join a server...
      2. Do something...
      3. See error...
  validations:
    required: true
- type: textarea
  id: screenshots
  attributes:
    label: "Screenshots"
    description: If applicable, add screenshots to help explain your problem.
    placeholder: |
      Drag and drop the screenshots here...
  validations:
    required: false
- type: textarea
  id: logs
  attributes:
    label: "Logs"
    description: If applicable, provide any crash reports or relevant logs have.
    placeholder: Copy-paste the log messages here...
    render: bash
  validations:
    required: false
- type: dropdown
  id: os
  attributes:
    label: "OS"
    description: What operating system are you using?
    options:
      - Windows 11
      - Windows 10
      - Windows 8/8.1
      - Windows 7
      - Windows Vista
      - Linux
      - Mac
  validations:
    required: false