        <tr><td colspan="3" nowrap>&nbsp;</td></tr>
        <tr>
		 <td colspan="3" nowrap>
          <table width="100%" border="1" cellpadding="5" cellspacing="0" bordercolor="#6C6C6C">
           <tr>
            <td class="nhbg" width=1% align="center" valign="middle">Player Name</td>
            <td class="shbg" align="center" width=1%>KILLS</td>
            <!-- if _RO_ -->
            <td class="shbg" align="center" width=1%>TEAM<br>KILLS</td>
            <!-- end _RO_ -->
            <td class="shbg" align="center" width=1%>DEATHS</td>
            <td class="shbg" align="center" width=1%>SUICIDES</td>
            <!-- if _RO_
            <td class="shbg" align="center" width=1%>SPREES</td>
            <td class="shbg" align="center" width=1%>MULTI<br>KILLS</td>
            end _RO_ -->
           </tr>
           <%StatRows%>
          </table>
         </td>
        <tr>
