//==============================================================================
// This file was automatically generated by the localization tool.
// Do not edit this file directly.
// To regenerate this file, run ./tools/localization/generate_fonts.bat
//==============================================================================

class DHLargeFont extends GUIFont;

event Font GetFont(int ResX)
{
    return class'DHFonts'.static.GetDHLargeFontByResolution(Controller.ResX, Controller.ResY);
}

defaultproperties
{
    KeyName="DHLargeFont"
}
