//==============================================================================
// This file was automatically generated by the localization tool.
// Do not edit this file directly.
// To regenerate this file, run ./tools/localization/generate_fonts.bat
//==============================================================================

class DHMenuFontDS extends GUIFont;

event Font GetFont(int ResX)
{
    return class'DHFonts'.static.GetDHMenuFontDSByResolution(Controller.ResX, Controller.ResY);
}

defaultproperties
{
    KeyName="DHMenuFontDS"
}
