<html>
<head>
<title><%Title%></title>
<meta http-equiv="Content-Type" content="text/html; charset=<%charset%>">
<link rel="stylesheet" type="text/css" href="<%CSS%>">
</head>
<body bgcolor="#161616" text="#ffffff" link="#a7b3e0" vlink="#a7b3e0" alink="#a7b3e0"
      topmargin="0" leftmargin="4" marginheight="0" marginwidth="0">

<table width="190" cellspacing="0" cellpadding="0" border="0" ID="Table1">
 <tr>
  <td width="12px"><img src="/images/q_topleft.gif"></td>
  <td background="/images/q_topmid.gif"><img src="/images/q_topmid.gif"></td>
  <td width="12px"><img src="/images/q_topright.gif"></td>
 </tr>
 <tr>
  <td width="12px" background="/images/q_left.gif"> </td>
  <td>
